language: php
php:
  - 5.3
  - 5.4

branches:
  except:
    - bundled

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1

before_script:
  - composer self-update
  - composer dump-autoload
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer install --dev --no-interaction --prefer-source; fi"

script:
  - sh -c "if [ '$COVERALLS' != '1' ]; then phpunit --stderr; else phpunit --stderr --coverage-clover build/logs/clover.xml; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -v; fi"
